Repository mapbox/ios-sdk-examples, pull requests merged in 2019-09, with the labels that each got.

#354 Update for Maps SDK for iOS v5.3.1
  Examples.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
Labels: maintenance

#356 Updated project for v5.3.2
  Examples.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
Labels: maintenance

#363 Work-around iOS 13 navigation controller rotation bug
  Examples/ExamplesContainerViewController.m
Labels: bug

#359 Add ShapeAnnotationsExample
  Examples.xcodeproj/project.pbxproj
  Examples/Examples.h
  Examples/Examples.m
  Examples/ObjectiveC/ShapeAnnotationsExample.h
  Examples/ObjectiveC/ShapeAnnotationsExample.m
  Examples/Swift/ShapeAnnotationsExample.swift
Labels: enhancement

#362 Remove DefaultAnnotationExample
  Examples.xcodeproj/project.pbxproj
  Examples/Examples.h
  Examples/Examples.m
  Examples/ObjectiveC/DefaultAnnotationExample.m
  Examples/ObjectiveC/Headers/DefaultAnnotationExample.h
  Examples/Swift/DefaultAnnotationExample.swift
Labels: maintenance
