Repository mapbox/ios-sdk-examples, pull requests merged in 2019-04, with the labels that each got.

#286 [ios] Add example for label placement.
  Examples.xcodeproj/project.pbxproj
  Examples/Examples.h
  Examples/Examples.m
  Examples/ObjectiveC/Headers/LabelPlacementExample.h
  Examples/ObjectiveC/LabelPlacementExample.m
  Examples/Swift/LabelPlacementExample.swift
Labels: new example

#293 Address ClusteringExample NSUInteger warnings
  Examples/ObjectiveC/ClusteringExample.m
Labels: bug

#294 Allow icon overlap for unclustered layer in ClusteringExample
  Examples/ObjectiveC/ClusteringExample.m
  Examples/Swift/ClusteringExample.swift
Labels: bug

#291 Navigation SDK v0.31.0
  Podfile
  Podfile.lock
Labels: maintenance
